server:
  port: 8000
spring:
  application:
    name: cambio-service
  cloud:
    zookeeper:
      discovery:
        enabled: true
      connect-string: localhost:2181
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cambio_service
    username: postgres
    password: demo
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    '[org.apache.zookeeper.ClientCnxn]': WARN